export type Theme = {
  id: string;
  label: string;
  pro: boolean;
  page: string;
  card: string;
  text: string;
  subtext: string;
  link: string;
  avatarBorder: string;
  bannerFallback: string;
  swatch: string;
};

export const THEMES: Theme[] = [
  {
    id: "default",
    label: "Padrão",
    pro: false,
    page: "bg-neutral-50",
    card: "bg-white hover:bg-neutral-50 text-neutral-900 shadow-sm hover:shadow-md",
    text: "text-neutral-900",
    subtext: "text-neutral-500",
    link: "border border-neutral-200",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-neutral-200 to-neutral-300",
    swatch: "bg-neutral-100",
  },
  {
    id: "sunset",
    label: "Sunset",
    pro: false,
    page: "bg-gradient-to-b from-orange-50 to-pink-50",
    card: "bg-white/90 hover:bg-white text-neutral-900 shadow-sm hover:shadow-md",
    text: "text-neutral-900",
    subtext: "text-neutral-600",
    link: "",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-orange-300 via-pink-300 to-rose-300",
    swatch: "bg-gradient-to-br from-orange-200 to-pink-200",
  },
  {
    id: "forest",
    label: "Forest",
    pro: false,
    page: "bg-emerald-50",
    card: "bg-white hover:bg-emerald-50 text-emerald-950 shadow-sm hover:shadow-md",
    text: "text-emerald-950",
    subtext: "text-emerald-700",
    link: "border border-emerald-200",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-emerald-300 to-teal-400",
    swatch: "bg-emerald-100",
  },
  {
    id: "ocean",
    label: "Ocean",
    pro: false,
    page: "bg-sky-50",
    card: "bg-white hover:bg-sky-50 text-sky-950 shadow-sm hover:shadow-md",
    text: "text-sky-950",
    subtext: "text-sky-700",
    link: "border border-sky-200",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-sky-300 to-blue-400",
    swatch: "bg-sky-100",
  },
  {
    id: "lavender",
    label: "Lavender",
    pro: false,
    page: "bg-violet-50",
    card: "bg-white hover:bg-violet-50 text-violet-950 shadow-sm hover:shadow-md",
    text: "text-violet-950",
    subtext: "text-violet-700",
    link: "border border-violet-200",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-violet-300 to-purple-300",
    swatch: "bg-violet-100",
  },
  {
    id: "mint",
    label: "Mint",
    pro: false,
    page: "bg-teal-50",
    card: "bg-white hover:bg-teal-50 text-teal-950 shadow-sm hover:shadow-md",
    text: "text-teal-950",
    subtext: "text-teal-700",
    link: "border border-teal-200",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-teal-300 to-cyan-300",
    swatch: "bg-teal-100",
  },
  {
    id: "midnight",
    label: "Midnight (PRO)",
    pro: true,
    page: "bg-neutral-950",
    card: "bg-white/[0.06] hover:bg-white/[0.1] text-white backdrop-blur border border-white/10",
    text: "text-white",
    subtext: "text-white/60",
    link: "",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-neutral-800 to-black",
    swatch: "bg-neutral-800",
  },
  {
    id: "gold",
    label: "Gold (PRO)",
    pro: true,
    page: "bg-gradient-to-b from-amber-950 via-neutral-950 to-neutral-950",
    card: "bg-amber-400/[0.08] hover:bg-amber-400/[0.15] text-amber-50 backdrop-blur border border-amber-400/20",
    text: "text-amber-50",
    subtext: "text-amber-200/70",
    link: "",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-amber-700 via-amber-900 to-neutral-950",
    swatch: "bg-gradient-to-br from-amber-500 to-amber-800",
  },
  {
    id: "gradient-pro",
    label: "Gradiente (PRO)",
    pro: true,
    page: "bg-gradient-to-br from-fuchsia-500 via-purple-500 to-indigo-600",
    card: "bg-white/15 hover:bg-white/25 text-white backdrop-blur border border-white/20",
    text: "text-white",
    subtext: "text-white/70",
    link: "",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-fuchsia-400 via-purple-400 to-indigo-500",
    swatch: "bg-gradient-to-br from-fuchsia-400 via-purple-400 to-indigo-500",
  },
  {
    id: "noir",
    label: "Noir (PRO)",
    pro: true,
    page: "bg-white",
    card: "bg-white hover:bg-neutral-50 text-neutral-950 border-2 border-neutral-950 shadow-none",
    text: "text-neutral-950",
    subtext: "text-neutral-500",
    link: "",
    avatarBorder: "border-neutral-950",
    bannerFallback: "bg-neutral-950",
    swatch: "bg-neutral-950",
  },
  {
    id: "candy",
    label: "Candy (PRO)",
    pro: true,
    page: "bg-gradient-to-b from-pink-100 via-fuchsia-50 to-yellow-50",
    card: "bg-white hover:bg-pink-50 text-neutral-900 shadow-md hover:shadow-lg",
    text: "text-neutral-900",
    subtext: "text-neutral-600",
    link: "border-2 border-pink-300",
    avatarBorder: "border-white",
    bannerFallback: "bg-gradient-to-br from-pink-400 via-fuchsia-400 to-yellow-300",
    swatch: "bg-gradient-to-br from-pink-300 via-fuchsia-300 to-yellow-200",
  },
];

export function getTheme(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}
